### PR TITLE
Set LatLngOverride to be removed to avoid error

### PR DESCRIPTION
**Pull request by jeffwhitfield**
Noticed that an error was happening due to the new LatLngOverride field. Added it to be removed prior to the new field being added back in. That fixes the issue!  :D

### CODE REVIEW

**Comment by sheadawson** [comment]
+1 please merge

**Comment by jeffwhitfield** [comment]
This fix appears to already been taken care of with commit #50. Closing. :P

**Comment by sheadawson** [comment]
Cool. Any chance of a release?

**Comment by jeffwhitfield** [comment]
Ok, this might make me sound really stupid but...what release? What are we talking about here? LOL!

**Comment by muskie9** [comment]
@jeffwhitfield a new [tag/release](https://github.com/silverstripe-australia/silverstripe-addressable/releases) of the module to run off of for composer, rather than running off of a dev branch like `dev-master` to pull the fix in.

**Comment by jeffwhitfield** [comment]
Sorry, meant to reference this commit:

https://github.com/silverstripe-australia/silverstripe-addressable/commit/2dbd6f7013561e4135850ee81999ece22ca73498

This one is already in master, which can be pulled in using `dev-master` for sure. This is the exact same fix as #50.

**Comment by sheadawson** [comment]
@jeffwhitfield master is considered a development branch, it may contain unstable/untested code. For this reason many developers prefer to only use stable releases of modules in their production projects. I wonder if @nyeholt can assist with this?

**Comment by jeffwhitfield** [comment]
@sheadawson Well, the problem is that a commit is already in master with the same exact fix. Not sure how that'll work. 

Also, is there any documentation on how the branching model works? Master being a development branch? That's new to me. In my experience, master is always production ready code but tagged release numbers. Development work should be in a separate branch away from Master. I'm not fond of mixing non-production with production code. That's a mess.

**Comment by sheadawson** [comment]
@jeffwhitfield Yeap, I was just requesting that master be tagged, no need to merge this commit, it's already in master. See http://semver.org/ for versioning guidelines. This module's latest stable release is 1.2.0 and was released a few months ago. This is the version I am currently using.

**Comment by nyeholt** [comment]
Have tagged 1.2.1

**Comment by sheadawson** [comment]
Cheers!

**Pull request closed without merging**
